### ISSUE TITLE
Fix error component in task-details page

### ISSUE THREAD

**Issue by k0malSharma** [Worktez/worktez#294]
**Describe the bug**
The error component is being displayed under the active model

**To Reproduce**
1. Go to the task-details page of any task
2. Click on log-work or edit-page
3. Incorrectly enter the data
4. See the error component pop up below the active model

**Expected behavior**
The error component is expected to be displayed above the model so that the error is made visible

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version: 94.0.4606.71

**Comment by sanjaykrishna1203** [comment]
Fixed in PR #398
